[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hydrostatics"
version = "0.1.0"
description = "Python sailboat hydrostatics library"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Eleanor Hall" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.20.0",
    "scipy>=1.11.0",
    "gmsh"
]

[project.optional-dependencies]
dev = [
    "sphinx>=7.0",
    "sphinx-rtd-theme",
    "numpydoc",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"] 